const vetData = [
    {
        name: "Garrix",
        phone: "0749348934",
        email: "garr@gmail.com",
        district: "Gasabo",
    },
    {
        name: "Garrix",
        phone: "0749348934",
        email: "garr@gmail.com",
        district: "Gasabo",
    },
    {
        name: "Garrix",
        phone: "0749348934",
        email: "garr@gmail.com",
        district: "Gasabo",
    },
    {
        name: "Garrix",
        phone: "0749348934",
        email: "garr@gmail.com",
        district: "Gasabo",
    },
    {
        name: "Garrix",
        phone: "0749348934",
        email: "garr@gmail.com",
        district: "Gasabo",
    },
    {
        name: "Garrix",
        phone: "0749348934",
        email: "garr@gmail.com",
        district: "Gasabo",
    },
    {
        name: "Mugisha",
        phone: "0749348934",
        email: "info@mug.com",
        district: "Nyarugenge",
    },
    {
        name: "Mugisha",
        phone: "0749348934",
        email: "info@mug.com",
        district: "Nyarugenge",
    },
    {
        name: "Mugisha",
        phone: "0749348934",
        email: "info@mug.com",
        district: "Nyarugenge",
    },
    {
        name: "Mugisha",
        phone: "0749348934",
        email: "info@mug.com",
        district: "Nyarugenge",
    },
    {
        name: "Mugisha",
        phone: "0749348934",
        email: "info@mug.com",
        district: "Nyarugenge",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Chelsea",
        phone: "0749348934",
        email: "chels@gmail.com.com",
        district: "Kicukiro",
    },
    {
        name: "Gatuzo",
        phone: "0749348934",
        email: "gatu@gmail.com",
        district: "Kicukiro",
    },
    {
        name: "Gatuzo",
        phone: "0749348934",
        email: "gatu@gmail.com",
        district: "Kicukiro",
    },
    {
        name: "Gatuzo",
        phone: "0749348934",
        email: "gatu@gmail.com",
        district: "Kicukiro",
    },
    {
        name: "Gatuzo",
        phone: "0749348934",
        email: "gatu@gmail.com",
        district: "Kicukiro",
    },
]

export default vetData